name: weather
description: A Weather App.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  geolocator: ^9.0.2
  http: ^0.13.5
  flutter_spinkit: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/


  fonts:
    - family: Spartan MB
      fonts:
        - asset: assets/fonts/SpartanMB-Black.otf
          weight: 900